version: '3.3'
services:
  # MySQL定義
  db:
    image: mysql:latest
    restart: always
    volumes:
      # 新規立ち上げ時にマウントしたボリューム内のSQLファイルを実行
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d/
      - ./mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      #- .\mysql\conf.d:/etc/mysql/conf.d
      #- .\mysql\log\ysql:/var/log/mysql
    environment: # MySQL 環境設定
      MYSQL_DATABASE: sample_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - 3306:3306
    
  # Flaskの定義
  flask:
    build: backend/
    volumes:
      - ./backend:/code
    environment:
      MYSQL_DATABASE: sample_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "5000:5000"
    command: flask run --host 0.0.0.0 --port 5000
    links:
      - db
    depends_on:
      - db